drishyadamodaran/hacktoberfest2021_CP

- Algorithms/job_sequencing.cpp
Making this code readable, Before it looks  ugly and has some spacing in it.
> Fix: Unstructured code

- Competitive programming/PYTHON/Find an Element in an array.py
Finding the element  in the array.
> How to find an Element in an array.py

- Competitive programming/C++/median_of_2_sorted_arrays.cpp
I have solved the Median of 2 Sorted Arrays (LeetCode Number 4) in C++.
Please review the PR and merge under the Hacktober tag.
> Median of 2 Sorted Arrays

- Algorithms/Merge_Sort-Iterative.c
- Algorithms/Merge_Sort-Recursive.c
> Added merge-sort in C language - iterative and recuursive

- Competitive programming/C++/FakeGCD.cpp
- Competitive programming/PYTHON/FAKESWAP.py
My solutions. I hope you label it too. :)
> Codechef Problems

- Competitive programming/C/matrix-addition.c
- Added Matrix_Addition C Program to your Repository
> Added Matrix-Addition C Program

- Competitive programming/JAVA/Binary_Tree_to_DLL.java
> Added Binary Tree to DLL Problem (GFG) in JAVA

- Algorithms/Merge_Sort.js
> Merge Sort in JavaScript

- Algorithms/kadane_algo.cpp
C++ program to print largest contiguous array sum using KADANE ALGORITHM
> New code kadane_algo.cpp

- Algorithms/BinarySearch
Binary Search implementation in C
> BinarySearch

- CompanywiseSolution/Amazon/Find Duplicates in array/question.txt
- CompanywiseSolution/Amazon/Find Duplicates in array/solution.java
Hey Please review my pr. I have added Find duplicates in an array question and solution
> Added a question and solution in Company wise

- Algorithms/Bubble_sort.cpp
Please merge, thankyou.
#Hacktoberfest2021
> Added Bubble_sort.cpp

- Algorithms/Z-Function.cpp
It is used to find the number of occurrences of one string in another string.
> Added z function algorithm

- Competitive programming/PYTHON/N_Queen.py
> feat:add nqueen problem

- Algorithms/remove_duplicates_in_sorted_array.cpp
Please merge the above CPP code of removing duplicates in a sorted array and add hacktoberfest tag.
> Adding remove_duplicates_in_sorted_array.cpp

- Competitive programming/PYTHON/knight_moves.py
> feat: add knight moves problem

- Algorithms/CreateHeap.cpp
- Algorithms/Diagnolmatrix.cpp
- Algorithms/HeapSort.c
- Algorithms/Heapify.cpp
- Algorithms/InsertHeap.cpp
- Algorithms/Kruskal'sMinSpanningTree.cpp
- Algorithms/LowerTriangularMatrix.cpp
- Algorithms/PrimsMinSpanningTree.cpp
- Algorithms/duplicate_elements_1.cpp
- Algorithms/duplicate_elements_using_hash.cpp
- Algorithms/missingelement.cpp
- Algorithms/missingusinghash.cpp
- Competitive programming/C++/InfixToPostfixUsingSTLStack.cpp
- Competitive programming/C++/PostfixEvaluation.cpp
- Competitive programming/C++/Tree.cpp
- Competitive programming/C++/extended_balanced_parenthesis_using_STL.cpp
- Competitive programming/C++/parenthesismatching.cpp
- Competitive programming/C++/stackLinkedList.cpp
Added some basic programming codes on the following:
- Arrays
- Binary Search Trees
- Stacks and Queues Implementation
- Graphs.
Hope this will help to grow more in the competitive programming platform.
> Competitive Code

- Algorithms/shellsort.cpp
> added shellsort.cpp

- Algorithms/Brian Kernighan’s Algorithm.py
Brian Kernighan’s Algorithm in python.
counting set bits code.
> Create Brian Kernighan’s Algorithm.py

- Competitive programming/C++/inverted_pattern.cpp
> Generate pattern

- Competitive programming/C++/MajorityElementInarray
- Competitive programming/C++/Move all zeroes to end
Added the Move All zeroes to end Code to folder
> Create Move all zeroes to end

- Competitive programming/C++/Symmetric_Tree.cpp
197 / 197 test cases passed.
Runtime: 0 ms
Memory Usage: 16.4 MB
> Add Symmetric Tree Question

- Competitive programming/C++/Permutation Minimization by Deque.c
Please merge my code for Hacktoberfest
> Permutation Minimization by Deque

- Competitive programming/C++/Print Subsets of Array.cpp
> Print subsets of an array using Recursion.

- Algorithms/Greedyalgo_coinchange.cpp
Created program for coin change problem which uses greedy algorithm.
> Created program for coin change problem

- Competitive programming/C++/Print all Codes - String(C++))
I have now put the file in the correct folder.
Thank you :)
> Create Print all Codes - String(C++))

- Competitive programming/C++/Move the elements.cpp
Program of Move the elements in c++.
> Move the elements.cpp

- CompanywiseSolution/ADOBE/Linked_List/question.md
- CompanywiseSolution/ADOBE/Linked_List/solution.cpp
Clone a linked list with next and random pointer
> Company Wise Coding Solutions

- Competitive programming/C++/Twins.cpp
this is solution of the problem of codefoces, div 2 TWINS
> Twins codeforces

- Competitive programming/C/ArmstrongNumber.c
- Competitive programming/C/Queus.c
- Competitive programming/C/Reflection.c
- Competitive programming/C/Searching for specific number in 1D array.c
- Competitive programming/C/Stacks.c
- Competitive programming/JAVA/Counting Sort.java
- Competitive programming/JAVA/MergeSort.java
- Competitive programming/JAVA/Recursive_Bubble_Sort.java
hey their 👋 
i add some programs
> add some java and c++ programs

- Competitive programming/C++/Codeforces_1560B.cpp
> Add Codeforces 1560B

- CompanywiseSolution/Amazon/Dynamic Programming/Minimum sum partition/question.md
- CompanywiseSolution/Amazon/Dynamic Programming/Minimum sum partition/solution.cpp
added question asked in amazon
> company wise solution

- Competitive programming/C++/Vanya and Lanterns.cpp
This is the solution of problem Vanya and lantenrs, codeforces round #280 div 2 problem.
the solution is in c++ programming language
> Vanya and Lanterns
